# {{name}}

An Angular component library workspace generated by Tateru.

## Commands

- `npm run create-component -- --name=MyButton` creates a publishable Angular library.
- `npm run create-css -- --name=DesignTokens` creates a publishable CSS package.
- `npm run build` builds every generated package with Angular's compiler and `ng-packagr`.
{{#tests}}
- `npm test` runs Vitest tests using Angular TestBed.
{{/tests}}
{{#eslint}}
- `npm run lint` runs ESLint.
{{/eslint}}
{{#stylelint}}
- `npm run lint-style` runs Stylelint.
{{/stylelint}}
{{#prettier}}
- `npm run format` formats the workspace with Prettier.
{{/prettier}}
{{#storybook}}
- `npm start` runs the Angular Storybook Webpack builder.
- `npm run build-storybook` builds the Storybook site.
{{/storybook}}

Generated package projects live under `packages/`. `tateru.json` records the framework and selected tools so later generators only create matching tests, stories, and targets.
