# {{name}}

A Solid component library workspace generated by Tateru.

## Commands

- `npm run create-component -- --name=MyButton` creates a publishable Solid package.
- `npm run create-css -- --name=DesignTokens` creates a publishable CSS package.
- `npm run build` builds generated packages with Vite and emits TypeScript declarations when applicable.
{{#tests}}
- `npm test` runs Vitest and Solid Testing Library tests.
{{/tests}}
{{#eslint}}
- `npm run lint` runs ESLint with Solid rules.
{{/eslint}}
{{#stylelint}}
- `npm run lint-style` runs Stylelint.
{{/stylelint}}
{{#prettier}}
- `npm run format` formats the workspace with Prettier.
{{/prettier}}

Generated package projects live under `packages/`. `tateru.json` records the framework and selected tools so later generators only create matching tests and targets.
